$(document).ready(function(){
    $("#subtract1").click(function(){
      $(".extra1").hide();
    });
    $("#add1").click(function(){
      $(".extra1").show();
    });
    $("#subtract2").click(function(){
      $(".extra2").hide();
    });
    $("#add2").click(function(){
      $(".extra2").show();
    });
    $("#subtract3").click(function(){
      $(".extra3").hide();
    });
    $("#add3").click(function(){
      $(".extra3").show();
    });
    $("#subtract4").click(function(){
      $(".extra4").hide();
    });
    $("#add4").click(function(){
      $(".extra4").show();
    });
});
